git-debimport texinfo_5.2.0.dfsg.1.orig.tar.xz

diff --git a/install-info/tests/defs.in b/install-info/tests/defs.in
--- a/install-info/tests/defs.in
+++ b/install-info/tests/defs.in
@@ -1,7 +1,7 @@
 # @configure_input@
-# $Id: defs.in,v 1.1 2008/04/17 17:54:17 karl Exp $
+# $Id: defs.in 5191 2013-02-23 00:11:18Z karl $
 # 
-# Copyright 2008 Free Software Foundation, Inc.
+# Copyright 2008, 2012 Free Software Foundation, Inc.
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -21,11 +21,12 @@
 SHELL='@SHELL@'
 export SHELL
 
-unset CDPATH
+# unsetting an already-unset variable fails with BSD sh.
+CDPATH=; unset CDPATH
 
 # Ensure we are running from the right directory.
 if test ! -f ./defs; then
-   echo "defs: not found in current directory" 1>&2
+   echo "$0: defs: not found in current directory." 1>&2
    exit 1
 fi
 
@@ -37,12 +38,69 @@ if test -z "$srcdir"; then
    test $srcdir = $0 && srcdir=.
 fi
 
-# The two variables we use in the test scripts.
-
+# Two variables we use in the test scripts:
 top_builddir=@top_builddir@
 install_info=${top_builddir}/install-info/ginstall-info
 export install_info
-
+#
 top_srcdir=@top_srcdir@
 testdir=${top_srcdir}/install-info/tests
 export testdir
+
+if test -z "$TMPDIR"; then
+  TMPDIR=/tmp
+  export TMPDIR
+fi
+
+# In case someone pedantic insists on using grep -E.
+: ${EGREP=egrep}
+
+# Systems which define $COMSPEC or $ComSpec use semicolons to separate
+# directories in TEXINPUTS -- except for Cygwin et al., where COMSPEC
+# might be inherited, but : is used.
+if test -n "$COMSPEC$ComSpec" \
+   && uname | $EGREP -iv 'cygwin|mingw|djgpp' >/dev/null; then
+  path_sep=";"
+else
+  path_sep=":"
+fi
+
+# Return true if PROG is somewhere in PATH, else false.
+findprog ()
+{
+  local saveIFS="$IFS"
+  IFS=$path_sep  # break path components at the path separator
+  for dir in $PATH; do
+    IFS=$saveIFS
+    # The basic test for an executable is `test -f $f && test -x $f'.
+    # (`test -x' is not enough, because it can also be true for directories.)
+    # We have to try this both for $1 and $1.exe.
+    #
+    # Note: On Cygwin and DJGPP, `test -x' also looks for .exe.  On Cygwin,
+    # also `test -f' has this enhancement, but not on DJGPP.  (Both are
+    # design decisions, so there is little chance to make them consistent.)
+    # Thusly, it seems to be difficult to make use of these enhancements.
+    #
+    if   { test -f "$dir/$1"     && test -x "$dir/$1"; } \
+      || { test -f "$dir/$1.exe" && test -x "$dir/$1.exe"; }; then
+      return 0
+    fi
+  done
+  return 1
+}
+
+if findprog mktemp; then :; else
+# Some deficient proprietary systems lack mktemp; kowtow to them.
+# Our mktemp substitute doesn't need all the features of real mktemp;
+# our tests here only use it in the most simplistic way, to create a
+# temp file.  The autoconf manual suggests doing it in a temporary
+# directory (mode 700).  ($RANDOM may expand to nothing, but that's ok.)
+# We do not even bother to expand the X's in the template ...
+mktemp ()
+{
+  dir=$TMPDIR/iimktemp$$-$RANDOM
+  (umask 077 && mkdir "$dir")
+  touch "$dir/$1" || return 1
+  echo "$dir/$1"
+}
+fi
